/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.post.transport.rmi;

import java.rmi.Remote;
import java.rmi.RemoteException;

/**
 * The invoice is generated by server.
 * @author kumari
 */
public interface Invoice extends Remote {
    
    /**
     * This returns id associated with invoice
     * @return
     * @throws RemoteException 
     */
    String getInvoiceId() throws RemoteException;
    
    /**
     * Returns sale object
     * @return
     * @throws RemoteException 
     */
    Sale getSale() throws RemoteException;
}
